### ISSUE TITLE
[Suggestion] get and modify the value of nbt tag

### ISSUE THREAD

**Issue by Til0mi** [jaylawl/jNBT#1]
Hi, and thanks for releasing this awesome addon!

I'm suggesting that the value (`<tagname>:<value>`) of a NBT tag could be obtained with a syntax something like `get nbt value of %nbt tag% on %item/entity/block%`

Also if you could modify the value, like
`(add|subtract) %number% (to|from) nbt value of tag %nbt tag% on %item/entity/block%`

Thanks :-)

**Comment by jaylawl** [comment]
Hey, i'm glad you're enjoying this addon. :)

I have somewhat added what you requested in 0.3. You can use `set {_value} to tag "Invulnerable" of entity's nbt` now - but keep in mind it will return a string. For now, you will have to parse for the calculations you want to do. Examply:
`set {_value} to tag "Invulnerable" of entity's nbt parsed as boolean`

I plan on adding automated parsing in the future though
