### ISSUE TITLE
[Suggestion] Support for sub-tags

### ISSUE THREAD

**Issue by Til0mi** [jaylawl/jNBT#4]
Support for sub-tags would be a great addition to this already awesome addon :-)

**Comment by jaylawl** [comment]
What are sub tags?

**Comment by Til0mi** [comment]
`{Items:[{Slot:0b,id:"minecraft:wooden_axe",Count:1b,Damage:0s}]}`
The tags inside the square brackets

**Comment by jaylawl** [comment]
@Til0mi please give me a skript-code example of how you would like it to work

**Comment by Til0mi** [comment]
I think the syntax should be something like `sub-tag "Slot" of "Items"`

Enchanted sword's NBT:
`{ench:[{lvl:3s,id:16s}],display:{Name:"test"}}`

So to get the enchantment id for example, we'd use something like `set {_enchantid} to sub-tag "id" of "ench" of held item's nbt`

But with a more complicated NBT (chests for example) this could get little tricky since there can be multiple sub-tags with same values..

But for me at least even a simple support for sub-tags would be a awesome addition since now the skript code to get a sub-value is little messy

**Comment by jaylawl** [comment]
that's already possible with `tag %string% of %nbt%`

**Comment by Til0mi** [comment]
![2018-09-06_15 43 03](https://user-images.githubusercontent.com/42693191/45158108-afd1e700-b1eb-11e8-8139-9f9b2db4f50c.png)
Well at least I can't get that to work

**Comment by jaylawl** [comment]
Try
`tag "lvl" of tag "ench" of held item's item-nbt`

**Comment by Til0mi** [comment]
![2018-09-06_15 53 04](https://user-images.githubusercontent.com/42693191/45158551-f83dd480-b1ec-11e8-86ca-44baa6b181b4.png)
Sadly that doesn't work either

**Comment by Til0mi** [comment]
Oh and console displays this error: `[14:58:41 WARN]: [Skript] NBT parse error: Expected '{' but got '[' at: [<--[HERE]`

**Comment by jaylawl** [comment]
oh, then just remove the [ ] brackets and it will work

**Comment by Til0mi** [comment]
But the problem is that they're sub-tags to the tag ench - that is default Mojang NBT and removing the brackets would cause the tag structure to break and so the whole NBT tag would be broken

So that's why I'm asking support for sub-tags :D

**Comment by Til0mi** [comment]
So uhm.. is this taken even in to consideration?

**Comment by jaylawl** [comment]
Not at the moment, maybe at some point. I'm really busy with trying to port this to 1.13

**Comment by Til0mi** [comment]
Okay, thanks anyway and a big thank-you for the upcoming 1.13 update :-)
